[build]
  publish = "client/dist"
  command = "cd client && npm install && npm run build && cp -r ../public/uploads ./dist/ || true"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

# 静态文件服务：uploads 目录中的文件直接提供，不经过重定向

# SPA 路由重定向：所有非API和非uploads请求都重定向到index.html，让React Router处理
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS" 